# Generated by Django 2.1.7 on 2019-02-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wine',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('designation', models.CharField(max_length=70)),
                ('points', models.IntegerField()),
                ('price', models.FloatField()),
                ('province', models.CharField(max_length=100)),
                ('region1', models.CharField(max_length=100)),
                ('region2', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('winery', models.CharField(max_length=100)),
            ],
        ),
    ]
